:imagesdir: assets/images/

== 四、Python语言元素

=== 1、创建python项目,为什么会有__init__.py文件生成？

  __init__.py 文件的作用是将文件夹变为一个Python模块,Python 中的每个模块的包中，都有__init__.py 文件。
 通常__init__.py 文件为空，但是我们还可以为它增加其他的功能。我们在导入一个包时，实际上是导入了它的__init__.py文件。这样我们可以在__init__.py文件中批量导入我们所需要的模块，而不再需要一个一个的导入。

#注意这里访问__init__.py文件中的引用文件，需要加上包名。__init__.py中还有一个重要的变量，__all__, 它用来将模块全部导入。#

=== 2、Python 中文编码

****

Python中默认的编码格式是 ASCII 格式，在没修改编码格式时无法正确打印汉字，所以在读取中文时会报错。

解决方法为只要在文件开头加入 # -*- coding:UTF-8 -*- 或者 # coding=utf-8 就行了

[TIP]
注意：# coding=utf-8 的 = 号两边不要空格。
****

=== 3、Python注释符

单行注释:::

[source,python,indent=5]
----
include::../chapter01/comments.py[lines=12..13]
----

多行注释:::

[source,python,indent=5]
----
include::../chapter01/comments.py[lines=14..22]
----

=== 4、Python 标识符

====
在 Python 里，标识符由字母、数字、下划线组成。

在 Python 中，所有标识符可以包括英文、数字以及下划线(_)，但不能以数字开头。

Python 中的标识符是区分大小写的。

以下划线开头的标识符是有特殊意义的。以单下划线开头 _foo 的代表不能直接访问的类属性，需通过类提供的接口进行访问，不能用 from xxx import * 而导入。

以双下划线开头的 __foo 代表类的私有成员，以双下划线开头和结尾的 __foo__ 代表 Python 里特殊方法专用的标识，如 __init__() 代表类的构造函数。

Python 可以同一行显示多条语句，方法是用分号 ;
====

=== 5、Python 保留字符

下面的列表显示了在Python中的保留字。这些保留字不能用作常数或变数，或任何其他标识符名称。 所有 Python 的关键字只包含小写字母。

.Python关键字
|===
|  |  |

|and
|exec
|not

|assert
|finally
|or

|break
|for
|pass

|class
|from
|print

|continue
|global
|raise

|def
|if
|return

|del
|import
|try

|elif
|in
|while

|else
|is
|with

|except
|lambda
|yield

|===

=== 6、行和缩进

====
学习 Python 与其他语言最大的区别就是，Python 的代码块不使用大括号 {} 来控制类，函数以及其他逻辑判断。python 最具特色的就是用缩进来写模块。

缩进的空白数量是可变的，但是所有代码块语句必须包含相同的缩进空白数量，这个必须严格执行。

====

I .正确行和缩进

[source,python,indent=0]
----
include::../chapter01/comments.py[lines=24..27]
----

II .错误行和缩进:::

[source,python,indent=0]
----
include::../chapter01/comments.py[lines=29..35]
----

[TIP]
#IndentationError: unindent does not match any outer indentation level错误表明，你使用的缩进方式不一致，有的是 tab 键缩进，有的是空格缩进，改为一致即可。 如果是 IndentationError: unexpected indent 错误, 则 python 编译器是在告诉你"Hi，老兄，你的文件里格式不对了，可能是tab和空格没对齐的问题"，所有 python 对格式要求非常严格。 因此，在 Python 的代码块中必须使用相同数目的行首缩进空格数。建议你在每个缩进层次使用 单个制表符 或 两个空格 或 四个空格 , 切记不能混用#

=== 7、多行语句

====
Python语句中一般以新行作为语句的结束符。但是我们可以使用斜杠（ \）将一行的语句分为多行显示，如下所示：
I .将一行的语句分为多行显示:::
[source,python,indent=0]
----
include::../chapter01/comments.py[lines=41..43]
----
II .语句中包含 [], {} 或 () 括号就不需要使用多行连接符。如下实例：:::
[source,python,indent=0]
----
include::../chapter01/comments.py[lines=44..46]
----
====

=== 8、Python 引号

====
Python 可以使用引号( ' )、双引号( " )、三引号( ''' 或 """ ) 来表示字符串，引号的开始与结束必须是相同类型的。

其中三引号可以由多行组成，编写多行文本的快捷语法，常用于文档字符串，在文件的特定地点，被当做注释。

[source,python,indent=0]
----
include::../chapter01/comments.py[lines=48..55]
----
====



